const NUMBER_OF_PARTICLES = 4000;
const NUMBER_OF_TERMS = 5;
const DELTA_TIME = 0.016;
const UNIVERSE_SIZE = 600;
const BOUNCE_DAMPENING = 0.8;

const FLOAT_TOLERANCE = 1e-7;
const GRAVITATIONAL_CONSTANT = 1.0;
